version: "3.9"

services:
  3x-ui:
    image: ghcr.io/mhsanaei/3x-ui:latest
    container_name: 3x-ui
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.3x-ui.rule=Host(`<Your host>`)"
      - "traefik.http.services.3x-ui.loadbalancer.server.port=2053"
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
    volumes:
      - "$PWD/cert/:/root/cert/"
      - "$PWD/db/:/etc/x-ui/"
    ports:
      - "<Your port>:2053"
      - "<Your tls port>:<Your tls port>"
    tty: true
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
